apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: ztgg-ui
  name: ztgg-ui-service
spec:
  type: NodePort
  ports:
    - name: ztgg-ui-port
      port: 3000 
      targetPort: 3000
      nodePort: 30003
  selector:
    io.kompose.service: ztgg-ui 
