apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: ztgg-backend-prod
  name: ztgg-backend-prod-service
spec:
  type: NodePort
  ports:
    - name: ztgg-backend-prod-port
      port: 5000
      targetPort: 5000
      nodePort: 30002
  selector:
    io.kompose.service: ztgg-backend-prod
